---
title: "First Knit"
author: "Jaelynn M. Schultz"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended Quartz Hill High School and graduated in 2021. As far as english and math is concerned, I have always been much better at english and english based classes. I performed best in english consistently throughout high school. 
     

## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
I have a windows computer. Rating myself from 1-10, I would say I am around a 5 or 6. I couldn't fix a computer if you asked, but I could figure out basic issues with effort. As for my internet access, the connection is pretty good.    

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     

I do not have any preference for what I am called. I have had professors shorten my name to Jae, some have called me by my last name, and others have come up with their own nicknames for me. It makes no difference to me.

## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
It is my goal to eventually become a political science professor. So obviously political science is of the greatest interest to me, and I am at the very least attempting to achieve a masters degree, if not a PhD.

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
I have never travelled outside of the United States. If I could go anywhere though, I would go to either London, England, or Dublin, Ireland. And no, I have never been in the military, although I have greatly considered doing so. My plan has always been to enter the Air Force if I were to actually join. 

## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




